# Programmazione in Python

Python è oggi uno dei linguaggi di programmazione più diffusi e viene utilizzato in numerosi ambiti, dallo sviluppo software alla Data Science, dal Machine Learning al calcolo scientifico. La sua popolarità è dovuta soprattutto alla sintassi chiara, alla grande disponibilità di librerie specializzate e a una comunità di sviluppatori molto ampia.

In questo corso daremo per acquisita una conoscenza di base del funzionamento e della sintassi di Python. Tuttavia, prima di affrontare le librerie e gli strumenti specifici per il calcolo numerico, in questo notebook richiameremo brevemente alcuni elementi fondamentali del linguaggio.

In particolare, rivedremo la definizione e l’uso delle variabili, i principali tipi di dato, gli operatori, le strutture condizionali e iterative, le principali strutture dati e la definizione di funzioni.

Questa introduzione non vuole essere un corso completo di programmazione in Python, ma un ripasso delle conoscenze necessarie per comprendere e svolgere le successive attività di laboratorio. Chi non ha sufficiente familiarità con la sintassi di base è invitato a integrare questo materiale con un tutorial completo.


## Premessa

In Python l’*indentazione* non ha soltanto una funzione grafica, ma fa parte della sintassi del linguaggio: viene utilizzata per identificare le istruzioni appartenenti allo stesso blocco di codice. Convenzionalmente, ogni livello di indentazione corrisponde a quattro spazi.

Un’indentazione mancante o incoerente produce un errore oppure modifica il significato del programma.

## (1) Tipi di dato

In Python ogni valore è un oggetto caratterizzato da un tipo. 

Precisamente, Python è un linguaggio **a tipizzazione dinamica**: quando si crea una variabile non è necessario dichiararne esplicitamente il tipo, perchè viene determinato automaticamente in base al valore assegnato.
NB: in Python il tipo appartiene all’oggetto, mentre una variabile è un nome che fa riferimento a quell’oggetto. Durante l’esecuzione, la stessa variabile può quindi essere associata a oggetti di tipo diverso.

Per conoscere il tipo dell’oggetto associato a una variabile si utilizza la funzione `type()`, che restituisce il tipo dell’oggetto ricevuto come argomento.

In [2]:
x = 5          # x fa riferimento a un oggetto di tipo int
print(type(x))

x = "ciao"     # ora x fa riferimento a un oggetto di tipo str
print(type(x))

<class 'int'>
<class 'str'>


Per comodità didattica distingueremo i tipi di dato elementari, che rappresentano singoli valori, dalle strutture dati, utilizzate per raccogliere e organizzare più valori.

### 1.1 Tipi di dato elementari

I tipi di dato elementari rappresentano singoli valori. I principali tipi predefiniti di Python sono:

* `int`, per i numeri interi;
* `float`, per i numeri in virgola mobile;
* `complex`, per i numeri complessi;
* `bool`, per i valori logici `True` e `False`;
* `str`, per le stringhe di caratteri;
* `NoneType`, il cui unico valore possibile è `None`, usato per indicare l’assenza di un valore.

In [ ]:
n = 12
x = 3.14
z = 2 + 3j
esito = True
testo = "Python"
risultato = None

print(type(n))          # <class 'int'>
print(type(x))          # <class 'float'>
print(type(z))          # <class 'complex'>
print(type(esito))      # <class 'bool'>
print(type(testo))      # <class 'str'>
print(type(risultato))  # <class 'NoneType'>

In [ ]:
n = float(n)
x = int(x)
esito = int(esito)
print(n, type(n))
print(x, type(x))
print(esito, type(esito))

> **Nota:** 
Python è **case-sensitive**: distingue cioè tra lettere maiuscole e minuscole. Pertanto, a e A sono due nomi di variabile distinti.


In [ ]:
# Define variables a and A
a = "Hello,"
A = "World!"

print(a)
print(A)

Il nome di una variabile:

* può contenere lettere, cifre e il carattere underscore _;
* non può iniziare con una cifra;
* non può contenere spazi o simboli come -, +, @, %, #;
* non può coincidere con una parola riservata di Python come if, for, while o class.


In [ ]:
numero_studenti = 25  # valido
x2 = 4.5              # valido
_valore = 10          # valido

2x = 5                # non valido: inizia con una cifra
numero-studenti = 25  # non valido: contiene un trattino
for = 3               # non valido: "for" è una parola riservata

#### Le f-string per la funzione print()


Le `f-string` (formatted string literals)  sono una modalità sintattica per costruire e formattare stringhe. Il risultato della valutazione di una f-string è un normale oggetto di tipo `str`.

Sono molto utili per rendere le stampe più comprensibili: consentono infatti di inserire direttamente all’interno di una stringa il valore di variabili o il risultato di espressioni. 

Si definiscono anteponendo la lettera f alla stringa e racchiudendo le espressioni tra parentesi graffe `{}` (placeholder).


In [ ]:
nome = "Anna"
eta = 21
messaggio = f"{nome} ha {eta} anni."
print(messaggio)
print(type(messaggio))  # <class 'str'>
print("\n")

x = 100//81
y = 100%81
print(f"100/81 = {100/81}")
print(f"\tLa divisione intera è: {x};")
print(f"\tL'operatore modulo (resto) è: {y}.")

x = 100/77
print(x)
print(f"\t Il valore arrotondato di x è: {x:0.4f}.")

x = 100/81
print(x)
print(f"\t Il valore arrotondato di x è: {x:0.4f}.")


Per maggiori informazioni sull'operatore di formattazione usato nel placeholder (cioè i `:` con le specifiche) e le opzioni di formattazione delle stringhe, fare riferimento al sito: https://www.w3schools.com/python/python_string_formatting.asp.

### 1.2 Strutture dati

Le strutture dati permettono di raccogliere e organizzare più valori all’interno di un unico oggetto. Tecnicamente, le strutture dati sono oggetti dotati di un tipo.

Python mette a disposizione diverse strutture dati predefinite, ciascuna adatta a esigenze differenti:

* le **liste** (`list`);
* le **tuple** (`tuple`);
* gli **intervalli** (`range`);
* gli **insiemi** (`set`);
* i **dizionari** (`dict`).


Le diverse strutture si distinguono principalmente per:

* ordine degli elementi;
* possibilità di essere modificate;
* possibilità di contenere duplicati;
* modalità di accesso agli elementi.

| Struttura | Ordinata | Modificabile |     Duplicati | Accesso         |
| --------- | -------: | -----------: | ------------: | --------------- |
| `list`    |       sì |           sì |            sì | mediante indice |
| `tuple`   |       sì |           no |            sì | mediante indice |
| `range`   |       sì |           no |            sì | mediante indice |
| `set`     |       no |           sì |            no | nessun indice   |
| `dict`    |   sì$^*$ |           sì | chiavi uniche | mediante chiave |

$^*$ Nei dizionari viene preservato l’ordine di inserimento degli elementi; tuttavia, gli elementi sono identificati e recuperati attraverso le loro chiavi, non attraverso una posizione numerica.


A differenza degli array numerici che vedremo successivamente, le strutture dati di Python possono generalmente contenere elementi di tipo diverso.

In [ ]:
dati = [10, 3.14, "Python", True] # lista

print(dati)
print(type(dati))

Le strutture possono anche essere annidate, cioè contenere altre strutture dati:

In [ ]:
dati = [
    ["Anna", 25],
    ["Luca", 28],
    ["Sara", 22]
]

print(type(dati))
print( dati[0] )
print(type(dati[0]))

#### Array di tipo `list`
Una lista è una sequenza ordinata e modificabile di elementi. Si definisce racchiudendo gli elementi tra parentesi quadre [] e separandoli con una virgola.

In [ ]:
numeri = [10, 120, 30, -40] 
nomi = ["Anna", "Maria", "Daniel", "Fatima", "Lucas", "Sara", "Mohamed", "Andrei", "Blerina"] 
lista_vuota = []

print(numeri)

Gli elementi di una lista sono identificati da un indice intero, la cui numerazione inizia da zero.
Gli indici negativi permettono di contare gli elementi a partire dalla fine: -1 indica l’ultimo elemento, -2 il penultimo e così via.

In [ ]:

print(numeri)
print("\n")

print(numeri[0]) 
print(numeri[2])  
print(numeri[-1]) 
print(nomi[2])
print(nomi[-2])

print(f"il massimo valore è: {max(numeri)}")
print(f"il minimo valore è: {min(numeri)}")

print(len(nomi)) # len restituisce il numero di elementi
# print(nomi[12])  # IndexError: list index out of range

> **Nota:** 
Le liste sono **modificabili** (mutable): è possibile sostituire, aggiungere o eliminare elementi dopo la loro creazione.


In [ ]:
nomi[0] = "Elena"
nomi.append("Amelia") # aggiunge un elemento in fondo 
# nomi[12] = "Amelia"
print(nomi)
print(len(nomi))


In [ ]:

numeri.sort() # ordina la lista 
print(numeri)
numeri.reverse() # inverte l'ordine degli elementi
print(numeri)


In [ ]:
nomi.sort()
print(nomi)
nomi.reverse()
print(nomi)

Attenzione che più varibili possono riferirsi allo stesso oggetto!

In [ ]:
a = [1, 2, 3]
b = a
b[0] = 10
print(a)
print(b)

x = [1, "2", "tre"]
y = x
y.append(False)
print(x)  

In [ ]:
c = a.copy()
c[0] = 20
print(a)
print(c)

#### Array di tipo `tuple`

Una **tupla** è una sequenza ordinata ma non modificabile. Si definisce generalmente racchiudendo gli elementi tra parentesi tonde.

In [ ]:
t = (1, True, "Hello")
print(t)
print(t[0])     
print(t[-1]) 
print(type(t))

Una tupla è **immutabile** (immutable): dopo la sua creazione non è possibile sostituire, aggiungere o eliminare elementi.

In [ ]:
t[0] = 4.0
# TypeError: 'tuple' object does not support item assignment

Le tuple sono utili per rappresentare collezioni di valori che non devono essere modificate, come coordinate, dimensioni o risultati multipli restituiti da una funzione (quest'ultima operazione è detta **unpacking**).

In [ ]:
nome, voto = ("Anna", 28) # tupla come output di una funzione

print(nome)
print(type(nome))
print(voto)

#### Array di tipo `range`
Come le tuple, anche gli oggetti di tipo `range` rappresentano sequenze ordinate, indicizzate ma immutabili. 
Un range contiene però solo numeri interi ed è utilizzato soprattutto nei cicli for.

In [ ]:
r = range(7) # 0, 1, 2, 3, 4, 5, 6

print(type(r)) 
print(len(r))   # 7
print(r[0])     # primo valore è 0
print(r[-1])    # il valore 7 è escluso

Un oggetto range non costruisce esplicitamente in memoria la lista completa dei valori. Per visualizzarli tutti, è possibile convertirlo in una lista

In [ ]:
print(r) 
print(list(r)) 

La sintassi generale è:  `range(inizio, fine, passo)`. Di default:
* l'inizio è 0
* il passo è 1

L'ultimo valore contenuto nel range è fine-passo 

In [ ]:
range(5)        # 0, 1, 2, 3, 4 
range(2, 6)     # 2, 3, 4, 5 
range(2, 10, 2) # 2, 4, 6, 8 
range(5, 0, -1) # 5, 4, 3, 2, 1

#### Lo slicing per le strutture ordinate

Lo slicing permette di estrarre una parte di una sequenza. La sintassi generale è:

`sequenza[inizio:fine:passo]`

L’elemento nella posizione inizio è incluso, mentre quello nella posizione fine è escluso.

In [ ]:
print(nomi)     
print(nomi[1:6])
print(nomi[1:6:2])

In [ ]:
print(nomi)
print(nomi[-1])
print(nomi[:4])     # parte da 0
print(nomi[4:])     # fino alla fine
print(nomi[::3])    # indico solo il passo
print(nomi[::-1])

## (2) Costrutti per il controllo del flusso

Le strutture di controllo permettono di stabilire quali istruzioni devono essere eseguite e in quale ordine. In particolare, le strutture condizionali consentono di eseguire un blocco di codice soltanto quando sono verificate determinate condizioni, mentre i cicli permettono di ripetere una o più istruzioni.

### 2.1 Struttura condizionale `if`

La sintassi generale per un `if` è:

```python
if <condizione>:
    <istruzioni>

elif <condizione_alternativa>:
    <istruzioni_alternative>

else:
    <istruzioni_finali>
```

Le istruzioni del blocco `if` vengono eseguite se la condizione è valutata come True. In caso contrario, vengono controllate le eventuali condizioni `elif`. Il blocco `else` viene eseguito se nessuna delle condizioni precedenti è verificata. L’indentazione identifica le istruzioni appartenenti a ciascun blocco.

I blocchi `elif` e `else` sono opzionali. Possono essere presenti più blocchi `elif`, ma un solo blocco `else`.

In [ ]:
# Define condition
condition = True

if condition:
    print("Condizione vera")
else:
    print("Condizione falsa")

Nelle condizioni, usiamo gli operatori di confronto e/o logici

In [ ]:
# Confronto
print(x == 0)
print(x != 0)
print(x < 0)
print(x <= 0)
print(x > 0)
print(x >= 0)

# Operatori logici: and (&), or (|), not (! or ~)
print(x > 0 and x < 10)
print(x < 0 or x > 10)
print(not x == 0)

### 2.2 Cicli `for` e `while`

Python mette a disposizione due principali strutture iterative:

- il ciclo `for`, che scorre gli elementi di un oggetto iterabile;
- il ciclo `while`, che ripete un blocco finché una condizione rimane vera.

La sintassi generale del ciclo `for` è:

```python
for <variabile> in <iterabile>:
    <istruzioni>
```

A ogni iterazione, la variabile assume il valore dell’elemento successivo dell’iterabile.
Liste, tuple, stringhe, dizionari, insiemi e oggetti range sono esempi di iterabili.

In [ ]:
print(nomi)
for nome in nomi:
    print(nome)

In [ ]:
for carattere in "Python":
    print(carattere)

In [ ]:
for i in range(5):
    print(i)

Il ciclo `while` ripete un blocco di istruzioni finché una condizione viene valutata come `True`:

```python
while <condizione>:
    <istruzioni>
```
È particolarmente utile quando il numero di iterazioni non è noto in anticipo.


In [ ]:
n = 5

while n > 0:
    print(n)  # print utile per tenere traccia delle iterazioni
    n -= 1

print("Fine!")

Per evitare cicli infiniti, è buona prassi controllare il `while` e fermarne l'esecuzione dopo un numero (predefinito, `maxit`) di iterazioni, con il comando `break`.

In [ ]:
# Inizializzazioni
cond = True
soglia = 50   # provare 50 e 500
maxit = 15      # massimo numero di iterazioni ammesse
i = 0           # counter

while cond:
    print(f"i = {i}, i² = {i**2}")

    if i**2 > soglia:
        print("Soglia superata.")
        cond = False

    i = i + 1 # Update
    # Controllo sul numero di iterazioni
    if i >= maxit:
        print("Numero massimo di iterazioni raggiunto.")
        break

## (3) Organizzazione del codice

Quando un programma cresce, è importante organizzarlo in modo chiaro, modulare e riutilizzabile. In questa sezione vedremo come definire funzioni, utilizzare moduli e pacchetti e gestire correttamente i percorsi di file e cartelle.

Introdurremo inoltre alcuni strumenti utili per valutare il comportamento del codice: la misurazione dei tempi di esecuzione e la lettura dei messaggi di errore, fondamentali per individuare e correggere eventuali problemi.

### 3.1 Funzioni

Una funzione è un blocco di codice riutilizzabile che esegue una determinata operazione. Può ricevere uno o più valori in ingresso e restituire uno o più risultati.

La sintassi generale è:

```python
def nome_funzione(parametro_1, parametro_2): 
    <istruzioni> 
    return risultato
```
I nomi presenti nella definizione sono detti parametri, mentre i valori forniti quando si richiama la funzione sono detti argomenti. Il `return` rende il risultato disponibile al resto del programma.

Per esempio, definiamo una funzione che somma due numeri:


In [ ]:
def somma(a, b):
    s = a + b

    return s

print(somma(3, 2))

Una funzione può restituire più valori, separandoli con una virgola. In questo caso, Python raccoglie automaticamente i risultati in una  `tupla`.

In [ ]:
def somma_e_prodotto(a, b): 
    somma = a + b 
    prodotto = a * b 
    return somma, prodotto

risultati = somma_e_prodotto(3, 2) 
print(type(risultati))  # <class 'tuple'>
print(risultati)        # (5, 6) 
print(risultati[0])
print(risultati[1])

È possibile assegnare direttamente i risultati a variabili distinte mediante l’unpacking:


In [ ]:
s, p = somma_e_prodotto(3, 2)
print(s) # 5 
print(p) # 6

Si possono definire anche funzioni senza un ritorno di variabili.
Se una funzione non contiene un’istruzione `return`, oppure esegue `return` senza indicare un valore, restituisce automaticamente `None`.

In [ ]:
def saluta(nome): 
    print(f"Buongiorno {nome}!") 

risultato = saluta("Anna") 
print(risultato)            # None 
print(type(risultato))      # <class 'NoneType'>

**Nota:**
in Python le funzioni sono oggetti, quindi possono essere assegnate a variabili e passate come argomenti ad altre funzioni.

Consideriamo una funzione matematica f(x), la sua derivata f'(x) e la formula
$$
x_{\mathrm{new}}=x-\frac{f(x)}{f'(x)},
$$
che rappresenta un passo del metodo di Newton per la ricerca degli zeri di (f).

Definiamo quindi una funzione `newton_step` che riceve come argomenti sia le funzioni `f` e `df` che un valore corrente di x:

In [ ]:
def f(x):       # un esempio di funzione derivabile
    return x**2 - 2 

def df(x):      # la derivata analitica deve esser calcolata a mano!
    return 2*x 

def newton_step(f, df, x): 
    return x - f(x) / df(x)

# Main: partendo da x=2, calcoliamo un passo del metodo di Newton
x = 2 
x_new = newton_step(f, df, x) 
print(x_new) 

Nella chiamata non si scrivono le parentesi dopo f e df. Infatti:

* `newton_step(f, df, x)`      passa le funzioni
* `newton_step(f(x), df(x), x)`  passa i valori ottenuti valutando le funzioni in x 


### 3.2 Moduli e pacchetti
Le funzionalità di base di Python possono essere ampliate mediante moduli e pacchetti, che raccolgono funzioni, costanti e altri strumenti già implementati. Nell’uso quotidiano, si adopera spesso la parola pacchetto in senso ampio per indicare un’intera libreria installabile, ma più precisamente:

* un modulo è normalmente un singolo file Python .py contenente funzioni, classi o variabili;
* un pacchetto è una cartella che organizza più moduli ed eventualmente altri sottopacchetti.

Alcuni moduli, come `os`, `math` e `random`, fanno parte della libreria standard e sono disponibili senza installazioni aggiuntive. Per utilizzarli è necessario importarli con il comando `import`, poi si accede agli elementi scrivendo il nome del modulo seguito da un punto:

In [ ]:
# Load in memoria
import os
import math
import random

print(os.getcwd())  # Current Working Directory
x = random.random() # Numero casuale nell'intervallo [0, 1)
y= math.exp(x)      # Esponenziale di x
print(x,y)

È possibile assegnare al modulo un nome abbreviato mediante la parola chiave `as`:

In [ ]:
import random as rnd

x = rnd.random()
print(x)

Si possono anche importare soltanto specifiche funzioni con `from` e `import`. In questo caso, le funzioni possono essere utilizzate senza anteporre il nome del modulo.

In [ ]:
from math import exp, sqrt

print(exp(1))       # non math.exp
print(sqrt(2))

**Nota**: il modulo `math` opera principalmente su *singoli* valori numerici. Per applicare funzioni matematiche a vettori, matrici o array si utilizza normalmente la libreria NumPy.

In [ ]:
# Costanti matematiche
x = math.pi       # π
y = math.e        # numero di Eulero
math.inf      # infinito
math.nan      # valore numerico non definito

print(f"pi = {x:0.6f}")
print(f"e = {y:0.6f}")

# Funzioni elementari
math.sqrt(x)     # radice quadrata
math.exp(x)      # esponenziale
math.log(x)      # logaritmo naturale
math.log10(x)    # logaritmo in base 10
math.factorial(n)# fattoriale di intero
math.pow(x, y)   # x elevato a y
x**y             # potenza
print(x**2)

In [ ]:
# Funzioni trigonometriche
math.sin(x)
math.cos(x)
math.tan(x)

# Funzioni di arrotondamento
math.floor(x)  # intero inferiore
math.ceil(x)   # intero superiore
math.trunc(x)  # elimina la parte decimale
math.fabs(x)   # valore assoluto

print(math.floor(x * 100) / 100)


Molti strumenti per il calcolo scientifico non appartengono alla libreria standard e devono essere installati separatamente come **pacchetti esterni**. Dal terminale, dopo aver attivato l’ambiente (virtual environment) Python corretto, è possibile usare:
```
python -m pip install nome_pacchetto
```

Se si utilizza un ambiente Conda, si può invece usare:

```
conda install nome_pacchetto
```
Dopo l’installazione, il pacchetto può essere importato normalmente:

In [ ]:
import numpy


I principali pacchetti utilizzati durante il corso saranno:

- `numpy` che offre gli strumenti di base per lavorare con array e matrici;
- `scipy` che aggiunge algoritmi scientifici più avanzati;
- `matplotlib` per l'elaborazione di grafici. 

## (4) Esercizi - parte 1: basi di python


### Esercizio 1. 
Assegna alle variabili `a`, `b` e `c` rispettivamente un intero, un numero decimale e una stringa. 
Stampa valore e tipo di ciascuna variabile.

Converti poi:
* a in un float;
* b in un int.

### Esercizio 2. 
Dati `a=17` e `b=5`, calcola e stampa:
* somma e prodotto;
* divisione, divisione intera e modulo resto;
* a elevato alla b;
* coseno di b.

### Esercizio 3. 
Definisci le variabili `studente` e `voto`, assegna rispettivamente un nome (Anna) e un intero (28), poi stampa la seguente frase utilizzando una f-stringa:
*Anna ha ottenuto 28/30*

### Esercizio 4. 
Definita la lista `numeri = [2, 5, 8, 11, 14, 17, 20]` estrai:
* i primi tre elementi;
* l'ultimo elemento
* gli elementi dall'8 al 17;
* gli elementi con indice pari;
* la lista in ordine inverso.

### Esercizio 5. 
Definisci un intero `n` (n>10), poi calcola con un ciclo `for` la la somma dei numeri interi da 1 a n (incluso). Stampa il risultato e aggiungi un controllo per stabilire se la somma è pari o dispari. 


### Esercizio 6. 
Scrivi una funzione `def media(a, b, c):` che restituisca la media di tre numeri. Richiamala con alcuni valori e stampa il risultato con due cifre decimali.

### Esercizio 7. 
Scrivi una funzione che riceva due numeri e restituisca:
* la loro somma;
* il loro prodotto;
* il maggiore dei due.

Recupera i tre risultati mediante unpacking.


## (5) NumPy

Numpy è la principale libreria Python per la rappresentazione e la manipolazione efficiente di vettori, matrici e array multidimensionali. Durante il corso utilizzeremo NumPy insieme a SciPy, che mette a disposizione algoritmi più avanzati per il calcolo scientifico.

**NOTA:** NumPy viene generalmente importato assegnandogli l’alias convenzionale `np`:
```python
import numpy as np
```
quindi tutte le sue funzioni saranno richiamate mediante il prefisso `np.`, per esempio:

In [ ]:
import numpy as np
x = np.sqrt(2)

print(x)

Se NumPy non è disponibile nell’ambiente Python, può essere installato dal terminale con:
```
python -m pip install numpy
```
oppure, in un ambiente Conda, con:
```
conda install numpy
```

Per maggiori informazioni è possibile consultare la documentazione ufficiale di NumPy [numpy.org](https://numpy.org).

### 5.1 Gli array `ndarray`
L'oggetto principale di `numpy` è il cosiddetto `ndarray`, che si usa per definire vettori, matrici e tensori "con proprietà" matematiche.

Un modo semplice per definire un `ndarray` è partire da oggetti python come `list` o `tuple`, poi convertirli in oggetto `np`:

In [3]:
import numpy as np

# Partiamo da una lista Python
a = [1, 2, 3]
print(type(a))

# Converto la lista in un numpy array
a = np.array(a)
print(a, type(a))

<class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [ ]:
# Caso per una matrice 3x3
A = [[1, 1, -1], [2, 0, 0], [0, 1, 2]]
A = np.array(A)

print(A)
print(A.shape)

In [ ]:
# Partiamo da una tupla Python
b = (1, -2, 11, 14, 52, 19)
print(b, type(b))

# Converto la tupla in un numpy array
b = np.array(b)
print(b, type(b))

# Converto l'array vettoriale in matrice
B = b.reshape((2,3))
print(f"B = {B}")
print(type(B))


Una proprietà importante degli array NumPy è la presenza di alcuni *attributi* che ne descrivono la struttura e il contenuto:

* `shape`: dimensione dell’array lungo ciascun asse;
* `ndim`: numero di dimensioni, o assi, dell’array;
* `size`: numero totale di elementi;
* `dtype`: tipo numerico degli elementi.
 

In [ ]:
print(a.shape)  # shape (3, )
print(a.ndim)
print(a.size)
print(a.dtype)

print(A.shape)
print(A.ndim)
print(A.size)
print(A.dtype)


Come per gli oggetti di Python, facciamo slicing su un vettore `v` usando la notazione `v[start:end:step] `. 

In [4]:
# Creazione dell'array
v = np.array([0, 3, -4, 2, 1, 7])
print(v)

# Slicing
print(v[1:3])
print(v[:3])
print(v[3:])
print(v[-1])

print(v[::2])
print(v[::-1])

[ 0  3 -4  2  1  7]
[ 3 -4]
[ 0  3 -4]
[2 1 7]
7
[ 0 -4  1]
[ 7  1  2 -4  3  0]


### 5.2 Creazione di vettori e matrici
Nelle applicazioni reali si lavora spesso con vettori e matrici di grandi dimensioni, che possono contenere milioni di elementi. Non è quindi possibile definirli inserendo manualmente tutti i valori. 

Quando i dati seguono una struttura particolare, NumPy mette a disposizione diverse funzioni per creare gli array in modo semplice ed efficiente.

* `np.linspace(a, b, n)`: crea un vettore contenente `n` valori equidistanti nell’intervallo chiuso $[a,b]$, estremi inclusi.
* `np.arange(start, end, step)`: crea un vettore di valori compresi tra `start` incluso e `end` escluso, con incremento `step`. 
* `np.zeros((m, n))`: crea una matrice $m \times n$ contenente solo zeri.  Nel caso di `np.zeros((m, ))` si ottiene un vettore.
* `np.ones((m, n))`: crea una matrice $m \times n$ contenente solo elementi uguali a uno.
* `np.zeros_like(a)`: crea un array di zeri con la stessa forma e lo stesso tipo di dato di `a`. Analogamente, si può usare `np.zeros(a.shape)`.
* `np.random.randn(m, n)`: crea una matrice $m \times n$ i cui elementi sono estratti indipendentemente da una distribuzione normale standard $\mathcal{N}(0, I)$.
* `np.eye(n)`: crea la matrice identità di ordine `n`.
* `np.diag(v)`: dato un vettore `v` di shape `(n,)`, crea una matrice diagonale $n \times n$ i cui elementi diagonali sono quelli di `v`.

In [ ]:
c = np.linspace(0, 1, 5) # array([0. , 0.25, 0.5 , 0.75, 1. ])
print(c)

d = np.arange(0, 20, 2)
print(d)

E = np.zeros((2, 3))
print(f"E={E}\n")

f = np.ones((6, ))
print(f)

g = np.zeros_like(d)
print(g)

rng = np.random.default_rng(42) 
H = rng.standard_normal((2, 3))
print(f"H={H}\n")

I = np.eye(3)
print(f"I={I}\n")

v = np.array([1, 2, 3]) 
L = np.diag(v)
print(f"L={L}")

### 5.3 Funzioni elemento-per-elemento su ```ndarray```

Molte funzioni NumPy hanno un corrispondente tra le funzioni di base di Python o nel modulo `math`, ma sono progettate per lavorare elemento per elemento sugli array.

In [ ]:
x = np.array([1, 4, 9, 16])

# Funzioni base
np.sqrt(x)   # al posto di math.sqrt()
print(np.sqrt(x))
np.exp(x)    # al posto di math.exp()
np.log(x)    # al posto di math.log()
np.sin(x)    # al posto di math.sin()
np.cos(x)    # al posto di math.cos()
np.abs(x)    # analoga ad abs()

# Operazioni di aggregazione
np.sum(x)     # analoga a sum()
np.min(x)     # analoga a min()
np.max(x)     # analoga a max()
np.mean(x)    # media
np.std(x)     # deviazione standard
print(np.std(x)) 



**Nota:** Mentre le liste sono strutture Python generiche e progettate per raccogliere anche oggetti di tipo diverso, gli array NumPy contengono invece elementi generalmente omogenei e sono progettati per eseguire operazioni numeriche *vettoriali* in modo compatto ed efficiente.

> Ne deriva che lo stesso operatore può assumere significati diversi a seconda del tipo di oggetto sul quale viene applicato!

Esempio 1:
* Per una lista Python, la moltiplicazione per un intero ripete gli elementi della lista;
* Per un array NumPy, invece, la moltiplicazione per uno scalare viene applicata elemento per elemento.

In [ ]:
# Attenzione!
x = [1, 2, 3]     # lista

x2 = x * 2             # [1, 2, 3, 1, 2, 3]
print(x2, type(x2))

x2 = np.array(x) * 2   # array([2, 4, 6])
print(x2, type(x2))



[1, 2, 3, 1, 2, 3] <class 'list'>
[2 4 6] <class 'numpy.ndarray'>


Esempio 2:
* Per una lista Python, la somma di liste è una concatenazione;
* Per un array NumPy, invece, la somma viene calcolata elemento per elemento.

In [6]:
a = [1, 2, 3] 
b = [4, 5, 6]      

print(a+b)                          # concatenazione
print( np.array(a)+np.array(b) )    # somma elemento per elemento

[1, 2, 3, 4, 5, 6]
[5 7 9]


### 5.4 Operazioni fra vettori e matrici

Per semplificare l’implementazione degli algoritmi di algebra lineare numerica, le operazioni fra gli array NumPy seguono essenzialmente la stessa sintassi utilizzata nei testi di matematica. Quindi, anche tutte (o quasi) le operazioni fra vettori e matrici vengono applicate elemento per elemento.

> Un’operazione fra due array $n$-dimensionali $a$ e $b$ si dice *elemento per elemento* quando viene applicata separatamente a ogni coppia di elementi corrispondenti di $a$ e $b$.

Per esempio, consideriamo i vettori:

$
a = \begin{bmatrix} 1 \\ 0 \\ -1 \end{bmatrix} \qquad b = \begin{bmatrix} 0 \\ 2 \\ 2 \end{bmatrix}
$

e la loro somma elemnt-wise è:

$
a + b = \begin{bmatrix} 1 + 0 \\ 0 + 2 \\ -1 + 2 \end{bmatrix} = \begin{bmatrix} 1 \\ 2 \\ 1 \end{bmatrix}.
$

Vediamo ora le principali operazioni elemento per elemento, fra due generici array NumPy `a` e `b` che hanno la stessa shape (vettori o matrici).
* a + b: restituisce la somma elemento per elemento di a e b.
* a - b: restituisce la differenza elemento per elemento fra a e b.
* a * b: restituisce il prodotto elemento per elemento di a e b. 
* a / b: restituisce il quoziente elemento per elemento fra a e b. 
* a ** b: eleva ogni elemento di a alla potenza indicata dal corrispondente elemento di b. 

Nell’algebra lineare numerica sono particolarmente importanti le operazioni di:
* prodotto matrice-vettore; 
* prodotto matrice-matrice; 
* prodotto scalare fra vettori. 

Poiché queste operazioni sono strettamente collegate dal punto di vista matematico, NumPy utilizza per tutte lo stesso operatore `@`: se le shape di due array `a` e `b` sono compatibili, `a @ b` esegue il loro prodotto corrispondente.


In [ ]:
import numpy as np

# Creazione della matrice
A = np.array([
    [1,  2, 0],
    [0, -1, 3],
   # [2,  1, 1]
])
print(A)

# Creazione dei vettori
x1 = np.array([1, 2, 3])
x2 = np.array([2, -1, 1])
print(x1)
print(x2)



[[ 1  2  0]
 [ 0 -1  3]]
[1 2 3]
[ 2 -1  1]


In [9]:
# Prodotto scalare
p = x1 @ x2
print(p)
print(x1*x2)  # Prodotto element-wise

# Il prodotto scalare fra due vettori può essere calcolato in modo equivalente mediante:
p2 = np.dot(x1, x2)
print(p2)


3
[ 2 -2  3]
3


In [8]:
# Prodotti matrice-vettore
y1 = A @ x1
y2 = A @ x2

print("A @ x1 =", y1)
print("A @ x2 =", y2)

A @ x1 = [5 7]
A @ x2 = [0 4]


In [ ]:
# Calcolo di A(x1 + x2)
y = A @ (x1 + x2)

# Verifica della proprietà distributiva
print (y == y1+y2)          # [ True  True]
np.array_equal(y, y1 + y2)  # True

## (6) Esercizi - parte 2: NumPy


### Esercizio 1.
Crea l’array NumPy `a = [2, 4, 6, 8, 10, 12]` e stampa:
* numero di dimensioni;
* shape;
* numero complessivo di elementi;
* tipo dei dati.

Successivamente crea la matrice `A` di shape (2, 3) dai valori di `a`, e stampa:
* A;
* shape;
* numero complessivo di elementi.


### Esercizio 2.
Considera i vettori lista `a = [1, 2, 3]` e `b = [4, 5, 6]`. Prevedi il risultato delle seguenti istruzioni:
* print(a + b)
* print(np.array(a) + np.array(b))
* print(3 * a)
* print(3 * np.array(a))
* print(a*b)
* print(np.array(a) * np.array(b))
* print(np.array(a) @ np.array(b))



### Esercizio 3.

Crea con NumPy un array `a` contenente `n` (n>4) numeri equispaziati, fra 0 a 18.

* Stampa l’array e la sua shape.
* Estrai i primi 3 elementi usando lo slicing.
* Seleziona gli elementi maggiori di 10 facendo uso di un vettore booleano (maschera logica).
* Calcola la somma e la media di tutti gli elementi di `a`.
* Crea un nuovo array `b` contenente i quadrati degli elementi di `a`.

### Esercizio 4.


Definisci `x = np.array([1, 2, -1])` e `A =  np.array([ [1,  2, 0],    [0, -1, 3],   [2,  1, 1] ])`, poi:
* Calcola a mano $Ax$;
* Verifica il risultato usando l’operatore @;
* Stampa la shape di A, di x e del risultato;
* Calcola A * x e spiega cosa rappresenta.