## Esercizio 3) Risoluzione di sistemi lineari

### Consegna: 

Considera le matrici

$$
A_1 = \begin{bmatrix}
10 &  2 & -1 &  1 &  0 \\
 2 &  9 &  1 & -2 &  1 \\
-1 &  1 &  7 &  1 & -1 \\
 1 & -2 &  1 &  8 &  2 \\
 0 &  1 & -1 &  2 &  6
\end{bmatrix}, \ \ \ \ 
A_2 = \begin{bmatrix} 1 & 2 \\ 2 & 1  \end{bmatrix} 
$$

e $A_3$ come matrice di Hilbert di dimensione n={2, 5, 15, 100}, poi:
* definisci il problema test $Ax=b$ per ciascuna matrice, usando come soluzione esatta il vettore di 1 di opportuna lunghezza;
* calcola il numero di condizionamento di A con `np.linalg.cond`;
* calcola la fattorizzazione LU con pivoting e quella di Cholesky (se opportuno) tramite le funzioni `lu` e `cholesky` di `scipy.linalg`;
* calcola l'errore (in norma) di fattorizzazione per A;
* risolvi il sistema lineare con le funzioni `lu_factor` e `lu_solve ` di `scipy.linalg` e calcola l'errore relativo sulla soluzione;
* quando possibile, risolvi il sistema con la fattorizzazione di Cholesky tramite la funzione `np.linalg.solve`  e calcola l'errore relativo sulla soluzione.


Definizione delle matrici

In [1]:
import numpy as np

# Caso 1
n = 5
A1 = np.array([[10,  2, -1,  1,  0],
              [ 2,  9,  1, -2,  1],
              [-1,  1,  7,  1, -1],
              [ 1, -2,  1,  8,  2],
              [ 0,  1, -1,  2,  6]], dtype=float)

# Caso 2
#n=2
#A2 = np.array([[1, 2],
#              [2, 1]], dtype=float)

# Caso 3
#from scipy.linalg import hilbert
#n = 15          # 2 oppure 5 oppure 100
#A3 = hilbert(n)




Definizione del sistema lineare

In [2]:
# Scelta della matrice
A = A1 # A1 oppure A2 oppure A3
print(f"A = {A}")

# Soluzione esatta 
x_esatta = np.ones(n)

# Calcolo del termine noto
b = A @ x_esatta
print(f"b = {b}")


A = [[10.  2. -1.  1.  0.]
 [ 2.  9.  1. -2.  1.]
 [-1.  1.  7.  1. -1.]
 [ 1. -2.  1.  8.  2.]
 [ 0.  1. -1.  2.  6.]]
b = [12. 11.  7. 10.  8.]


In [3]:
print(np.linalg.cond(A))

4.12531876645202


Calcolo le fattorizzazioni

In [4]:
from scipy.linalg import lu, cholesky

P, L, U = lu(A)
print("P:\n", P)
print("L:\n", L)
print("U:\n", U)

print("Errore fattorizzazione LU:",
      np.linalg.norm(A - P @ L @ U))


P:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
L:
 [[ 1.          0.          0.          0.          0.        ]
 [ 0.2         1.          0.          0.          0.        ]
 [-0.1         0.13953488  1.          0.          0.        ]
 [ 0.1        -0.25581395  0.208981    1.          0.        ]
 [ 0.          0.11627907 -0.16925734  0.35409514  1.        ]]
U:
 [[10.          2.         -1.          1.          0.        ]
 [ 0.          8.6         1.2        -2.2         1.        ]
 [ 0.          0.          6.73255814  1.40697674 -1.13953488]
 [ 0.          0.          0.          7.04317789  2.49395509]
 [ 0.          0.          0.          0.          4.8077489 ]]
Errore fattorizzazione LU: 2.7194799110210365e-16


In [5]:
C = cholesky(A, lower=True)
print("C:\n", C)

print("Errore fattorizzazione Cholesky:",
      np.linalg.norm(A - C @ C.T))

C:
 [[ 3.16227766  0.          0.          0.          0.        ]
 [ 0.63245553  2.93257566  0.          0.          0.        ]
 [-0.31622777  0.4091966   2.59471735  0.          0.        ]
 [ 0.31622777 -0.75019377  0.54224663  2.65389862  0.        ]
 [ 0.          0.34099717 -0.43917496  0.93973262  2.19265795]]
Errore fattorizzazione Cholesky: 2.286089127109703e-15


Risoluzione del sistema lineare tramite LU con pivoting

In [6]:
# Risoluzione mediante LU con pivoting
from scipy.linalg import lu_factor, lu_solve

lu, piv = lu_factor(A)
x_lu = lu_solve((lu, piv), b)


In [8]:
# Per la risoluzione con LU
errore_relativo_lu = np.linalg.norm(x_lu - x_esatta) / np.linalg.norm(x_esatta)

print("Termine noto b:", b)
print("Soluzione esatta:", x_esatta)
print("Soluzione calcolata:", x_lu)
print(f"Errore relativo: {errore_relativo_lu:.3e}")

Termine noto b: [12. 11.  7. 10.  8.]
Soluzione esatta: [1. 1. 1. 1. 1.]
Soluzione calcolata: [1. 1. 1. 1. 1.]
Errore relativo: 1.986e-16


Risoluzione del sistema lineare tramite Cholesky

In [ ]:
# Risoluzione mediante Cholesky dei due sistemi: Ly = b e L.T x = y
y = np.linalg.solve(C, b)
x_chol = np.linalg.solve(C.T, y)


In [11]:
# Per la risoluzione con Chol
errore_relativo_chol = np.linalg.norm(x_chol - x_esatta) / np.linalg.norm(x_esatta)

print("Termine noto b:", b)
print("Termine di appoggio y:", y)
print("Soluzione esatta:", x_esatta)
print("Soluzione calcolata:", x_chol)
print(f"Errore relativo: {errore_relativo_chol:.3e}")

Termine noto b: [12. 11.  7. 10.  8.]
Termine di appoggio y: [3.79473319 2.93257566 2.69778903 3.59363124 2.19265795]
Soluzione esatta: [1. 1. 1. 1. 1.]
Soluzione calcolata: [1. 1. 1. 1. 1.]
Errore relativo: 2.895e-16
