## Esercizio 3) Risoluzione di sistemi lineari

### Consegna: 

Considera le matrici

$$
A_1 = \begin{bmatrix}
10 &  2 & -1 &  1 &  0 \\
 2 &  9 &  1 & -2 &  1 \\
-1 &  1 &  7 &  1 & -1 \\
 1 & -2 &  1 &  8 &  2 \\
 0 &  1 & -1 &  2 &  6
\end{bmatrix}, \ \ \ \ 
A_2 = \begin{bmatrix} 1 & 2 \\ 2 & 1  \end{bmatrix} 
$$

e $A_3$ come matrice di Hilbert di dimensione n={2, 5, 15, 100}, poi:
* definisci il problema test $Ax=b$ per ciascuna matrice, usando come soluzione esatta il vettore di 1 di opportuna lunghezza;
* calcola il numero di condizionamento di A con `np.linalg.cond`;
* calcola la fattorizzazione LU con pivoting e quella di Cholesky (se opportuno) tramite le funzioni `lu` e `cholesky` di `scipy.linalg`;
* calcola l'errore (in norma) di fattorizzazione per A;
* risolvi il sistema lineare con le funzioni `lu_factor` e `lu_solve ` di `scipy.linalg` e calcola l'errore relativo sulla soluzione;
* quando possibile, risolvi il sistema con la fattorizzazione di Cholesky tramite la funzione `np.linalg.solve`  e calcola l'errore relativo sulla soluzione.


Definizione delle matrici

In [1]:
import numpy as np

# Caso 1
n = 5
A1 = np.array([[10,  2, -1,  1,  0],
              [ 2,  9,  1, -2,  1],
              [-1,  1,  7,  1, -1],
              [ 1, -2,  1,  8,  2],
              [ 0,  1, -1,  2,  6]], dtype=float)

# Caso 2
#n=2
#A2 = np.array([[1, 2],
#              [2, 1]], dtype=float)

# Caso 3
#from scipy.linalg import hilbert
#n = 15          # 2 oppure 5 oppure 100
#A3 = hilbert(n)




Definizione del sistema lineare

In [2]:
# Scelta della matrice
A = A1 # A1 oppure A2 oppure A3
print(f"A = {A}")

# Soluzione esatta 
x_esatta = np.ones(n)

# Calcolo del termine noto
b = A @ x_esatta
print(f"b = {b}")


A = [[10.  2. -1.  1.  0.]
 [ 2.  9.  1. -2.  1.]
 [-1.  1.  7.  1. -1.]
 [ 1. -2.  1.  8.  2.]
 [ 0.  1. -1.  2.  6.]]
b = [12. 11.  7. 10.  8.]


In [3]:
print(np.linalg.cond(A))

4.12531876645202


Calcolo le fattorizzazioni

In [1]:
from scipy.linalg import lu, cholesky
#...


Risoluzione del sistema lineare tramite LU con pivoting

In [ ]:
from scipy.linalg import lu_factor, lu_solve
# ...

Risoluzione del sistema lineare tramite Cholesky

In [ ]:
# Risoluzione mediante Cholesky dei due sistemi: Ly = b e L.T x = y
# ...
# np.linalg.solve(...)
